<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class UserTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now('Asia/Ho_Chi_Minh')->toDateTimeString();
        DB::table('users')->insert([
            [
                'email' => 'admin@example.com',
                'name' => 'Admin',
                'id_user' => 'admin',
                'password' => Hash::make('123456'),
                'deparment_id' => 1,
                'role_id' => 1,
                'status' => 1,
                'created_at' => $now,
                'updated_at' =>  $now,
                'deleted_at' => null,
            ],
             [
                'email' => 'cantn@example.com',
                'name' => 'Tạ Năm Cân',
                'id_user' => 'cantn',
                'password' => Hash::make('123456'),
                'deparment_id' => 1,
                'role_id' => 1,
                'status' => 1,
                'created_at' => $now,
                'updated_at' =>  $now,
                'deleted_at' => null,
             ],
             [
                'email' => 'liemhv@example.com',
                'name' => 'Hoàng Vương Liệm',
                'id_user' => 'liemhv',
                'password' => Hash::make('123456'),
                'deparment_id' => 1,
                'role_id' => 1,
                'status' => 1,
                'created_at' => $now,
                'updated_at' =>  $now,
                'deleted_at' => null,
             ],
             [
                'email' => 'nhantqm@example.com',
                'name' => 'Tuyền Quang Minh Nhân',
                'id_user' => 'nhantqm',
                'password' => Hash::make('123456'),
                'deparment_id' => 1,
                'role_id' => 1,
                'status' => 1,
                'created_at' => $now,
                'updated_at' =>  $now,
                'deleted_at' => null,
             ],
             [
                'email' => 'hiepnh@example.com',
                'name' => 'Nguyễn Hoàng Hiệp',
                'id_user' => 'hiepnh',
                'password' => Hash::make('123456'),
                'deparment_id' => 1,
                'role_id' => 1,
                'status' => 1,
                'created_at' => $now,
                'updated_at' =>  $now,
                'deleted_at' => null,
             ],
             [
                'email' => 'haithl@example.com',
                'name' => 'Trần Hoàng Long Hải',
                'id_user' => 'hainv',
                'password' => Hash::make('123456'),
                'deparment_id' => 2,
                'role_id' => 2,
                'status' => 1,
                'created_at' => $now,
                'updated_at' =>  $now,
                'deleted_at' => null,
             ],
             [
                'email' => 'thanhnk@example.com',
                'name' => 'Nguyễn Khánh Thành',
                'id_user' => 'thanhnk',
                'password' => Hash::make('123456'),
                'deparment_id' => 2,
                'role_id' => 3,
                'status' => 1,
                'created_at' => $now,
                'updated_at' =>  $now,
                'deleted_at' => null,
             ],
             [
                'email' => 'cunt@example.com',
                'name' => 'Nguyễn Trọng Cừ',
                'id_user' => 'cunt',
                'password' => Hash::make('123456'),
                'deparment_id' => 3,
                'role_id' => 3,
                'status' => 1,
                'created_at' => $now,
                'updated_at' =>  $now,
                'deleted_at' => null,
             ],
             [
                'email' => 'taohn@example.com',
                'name' => 'Hoàng Nhật Tảo',
                'id_user' => 'taohn',
                'password' => Hash::make('123456'),
                'deparment_id' => 2,
                'role_id' => 3,
                'status' => 1,
                'created_at' => $now,
                'updated_at' =>  $now,
                'deleted_at' => null,
             ],
             [
                'email' => 'satnc@example.com',
                'name' => 'Nguyễn Cảnh Sát',
                'id_user' => 'satnc',
                'password' => Hash::make('123456'),
                'deparment_id' => 3,
                'role_id' => 3,
                'status' => 1,
                'created_at' => $now,
                'updated_at' =>  $now,
                'deleted_at' => null,
             ],
             [
                'email' => 'quoctt@example.com',
                'name' => 'Trần Trung Quốc',
                'id_user' => 'quoctt',
                'password' => Hash::make('123456'),
                'deparment_id' => 4,
                'role_id' => 3,
                'status' => 1,
                'created_at' => $now,
                'updated_at' =>  $now,
                'deleted_at' => null,
             ],
             [
               'email' => 'hieunm@example.com',
               'name' => 'Nguyễn Minh Hiếu',
               'id_user' => 'hieunm',
               'password' => Hash::make('123456'),
               'deparment_id' => 5,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'chimy@example.com',
               'name' => 'Mai Yến Chi',
               'id_user' => 'chimy',
               'password' => Hash::make('123456'),
               'deparment_id' => 3,
               'role_id' => 2,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'trangdh@example.com',
               'name' => 'Đường Huyền Trang',
               'id_user' => 'trangdh',
               'password' => Hash::make('123456'),
               'deparment_id' => 5,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'hauvh@example.com',
               'name' => 'Vương Hoàng Hậu',
               'id_user' => 'hauvh',
               'password' => Hash::make('123456'),
               'deparment_id' => 4,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'loht@example.com',
               'name' => 'Hoàng Trung Lộ',
               'id_user' => 'loht',
               'password' => Hash::make('123456'),
               'deparment_id' => 5,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'thunx@example.com',
               'name' => 'Nguyễn Xuân Thu',
               'id_user' => 'thunx',
               'password' => Hash::make('123456'),
               'deparment_id' => 4,
               'role_id' => 2,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'thuydt@example.com',
               'name' => 'Đỗ Thanh Thủy',
               'id_user' => 'thuydt',
               'password' => Hash::make('123456'),
               'deparment_id' => 2,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'hainh@example.com',
               'name' => 'Nguyễn Hoàng Hải',
               'id_user' => 'hainh',
               'password' => Hash::make('123456'),
               'deparment_id' => 3,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'tups@example.com',
               'name' => 'Phạm Sinh Tử',
               'id_user' => 'tups',
               'password' => Hash::make('123456'),
               'deparment_id' => 5,
               'role_id' => 2,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'tungnui@example.com',
               'name' => 'Nguyễn Thanh Tùng',
               'id_user' => 'tungnui',
               'password' => Hash::make('123456'),
               'deparment_id' => 2,
               'role_id' => 2,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'boitn@example.com',
               'name' => 'Trần Ngọc Bội',
               'id_user' => 'boitn',
               'password' => Hash::make('123456'),
               'deparment_id' => 4,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'truongnt@example.com',
               'name' => 'Nguyễn Thanh Trường',
               'id_user' => 'truongnt',
               'password' => Hash::make('123456'),
               'deparment_id' => 3,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'khivtn@example.com',
               'name' => 'Võ Trọng Nghĩa Khí',
               'id_user' => 'khivtn',
               'password' => Hash::make('123456'),
               'deparment_id' => 4,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'tannn@example.com',
               'name' => 'Nguyễn Ngọc Tân',
               'id_user' => 'tannn',
               'password' => Hash::make('123456'),
               'deparment_id' => 2,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'tuyetqtm@example.com',
               'name' => 'Quách Thị Mai Tuyết',
               'id_user' => 'tuyetqtm',
               'password' => Hash::make('123456'),
               'deparment_id' => 5,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'child@example.com',
               'name' => 'Lương Đình Chi',
               'id_user' => 'child',
               'password' => Hash::make('123456'),
               'deparment_id' => 2,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'tont@example.com',
               'name' => 'Ngô Tất Tố',
               'id_user' => 'tont',
               'password' => Hash::make('123456'),
               'deparment_id' => 4,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'hoanglv@example.com',
               'name' => 'Lê Văn Hoàng',
               'id_user' => 'hoanglv',
               'password' => Hash::make('123456'),
               'deparment_id' => 5,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
            [
               'email' => 'longnqk@example.com',
               'name' => 'Nguyễn Quang Khải Long',
               'id_user' => 'longnqk',
               'password' => Hash::make('123456'),
               'deparment_id' => 2,
               'role_id' => 3,
               'status' => 1,
               'created_at' => $now,
               'updated_at' =>  $now,
               'deleted_at' => null,
            ],
        ]);
    }
}
